language: objective-c
osx_image: xcode8
env:
- DESTINATION="OS=10.0,name=iPhone 7" SCHEME="Hosyou" SDK=iphonesimulator10.0

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -workspace Hosyou.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project Hosyou.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
