language: objective-c
osx_image: xcode8
env:
 - DESTINATION="OS=10.0,name=iPhone 7" 
 - SDK=iphonesimulator10.0

xcode_workspace: Hosyou.xcworkspace
xcode_scheme: Hosyou

script:
- xcodebuild clean build -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
