language: objective-c
osx_image: xcode8
xcode_workspace: Hosyou.xcworkspace
xcode_scheme: Hosyou

script:
- xcodebuild test -workspace Hosyou.xcworkspace -scheme Hosyou -sdk iphonesimulator

after_success:
  - bash <(curl -s https://codecov.io/bash)
